account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('create/', views.signup, name='create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from sw import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sw/', include('sw.urls')),
    path('account/', include('account.urls')),
    path('', views.home),
]

sw/urls.py
from django.urls import path

from . import views


app_name = 'sw'


urlpatterns = [
    # 메인페이지
    path('', views.home, name='home'),
    # 학생회 소개
    path('swintro/', views.introduce, name='swintro'),
    # 학생회 연혁
    path('swhistory/', views.history, name='swhistory'),
]

account/models.py
from django.db import models

# Create your models here.

sw/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# create account관련된 UserCreatinForm 상속받아서
# 사용자지정 form class UserForm 생성
class UserForm(UserCreationForm):
    # 사용자 지정 form(학번, 이메일, 증명 이미지)을 통해
    # 우리가 원하는 form을 받을 수 있게 미리 정의함
    stdnumber = forms.Field(label="학번")
    email = forms.EmailField(label="이메일")
    veriImg = forms.ImageField(label="증명사진")

    class Meta:
        model = User
        fields = ("stdnumber", "username", "veriImg", "password1", "password2", "email")

account/views.py
# 계정관련 app 정의 부분
# 계정 생성 및 로그인과 관련된 request, action을 정의하고 있다.
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from account.forms import UserForm
from django.contrib import messages
from django.contrib import auth


# 로그인 및 회원가입 view


def login(request):
    return render(request, 'login.html')


# 회원가입 action

def signup(request):
    if request.method == "POST":
        if request.POST['passworld1'] == request.POST['password2']:
            user = User.objects.create_user(username=request.POST['name'], password=request.POST['password1'],
                                            stdnumber=request.POST['stdnumber'], email=request.POST['email'],
                                            veriImg=request.POST['veriImg'])
            auth.login(request, user)
            return redirect('/')
    return render(request, 'register.html')

sw/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.


def home(request):
    return render(request, 'index.html')


def introduce(request):
    return render(request, 'swintro.html')


def history(request):
    return render(request, 'swhistory.html')

templates/Doc/index.html
<!DOCTYPE html>
<html class="no-js">
<head>
	<meta charset="utf-8">
	<title>Hosting</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet'>
	<!-- Syntax Highlighter -->
	<link rel="stylesheet" type="text/css" href="syntax-highlighter/styles/shCore.css" media="all">
	<link rel="stylesheet" type="text/css" href="syntax-highlighter/styles/shThemeDefault.css" media="all">
	<!-- Font Awesome CSS-->
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<!-- Normalize/Reset CSS-->
	<link rel="stylesheet" href="css/normalize.min.css">
	<link rel="stylesheet" href="css/main.css">
</head>

<body id="welcome">
<aside class="left-sidebar">
<div class="logo">
	<a href="#welcome">
		<h1>Hosting</h1>
	</a>
</div>
<nav class="left-nav">
	<ul id="nav">
		<li class="current"><a href="#welcome">Welcome</a></li>
		<li><a href="#installation">Installation</a></li>
		<li><a href="#tmpl-structure">Structure</a></li>
		<li><a href="#css-structure">CSS Files</a></li>
		<li><a href="#javascript">JavaScript Libraries</a></li>
		<li><a href="#contact-form">Contact Form</a></li>
		<li><a href="#subscription-form">Subscription Form</a></li>
		<li><a href="#video">Video Tutorial</a></li>
		<li><a href="#credit">Source and Credit</a></li>
	</ul>
</nav>
</aside>
<!-- Main Wrapper -->
<div id="main-wrapper">
	<div class="main-content">
		<section id="welcome">
			<div class="content-header">
				<h1>Hosting</h1>
			</div>
			<div class="welcome">
				<h2 class="twenty">Welcome To Hosting</h2>
				<p>Firstly, a huge thanks for purchasing this theme, your support is truly appreciated!</p>
				<p>This document covers the installation and use of this theme and often reveals answers to common problems and issues - read this document thoroughly if you are experiencing any difficulties. If you have any questions that are beyond the scope of this document. Thank you so much!</p>
			</div>
			<div class="features">
				<h2 class="twenty">Template Features</h2>
				<ul>
					<li>Clean &amp; Simple Design</li>
					<li>HTML5 &amp; CSS3</li>
					<li>Fully Responsive Design</li>
					<li>PHP/Ajax Powered Working Contact Form</li>
					<li>All files are well commented</li>
					<li>Cross Browser Compatible with IE11+, Firefox, Safari, Opera, Chrome</li>
					<li>Extensive Documentation</li>
				</ul>
			</div>
		</section>
		<section id="installation">
			<div class="content-header">
				<h1>Hosting</h1>
			</div>
			<h2 class="title">Installing Template.</h2>
			<div class="section-content">
				<ol>
					<li>After unzip the download pack, you'll found a Template Folder with all the files.</li>
					<li>You can view this Template in any browser, you can display or edit the Template without an internet connection.(May not wotrk fonts and google map).</li>
					<li>The only section that will not work is the Contact Section which contains PHP code and requires a server environment for send messages.</li>
					<li>Now go to your cpanel or open your FTP Client (like <a target="_blank" href="https://filezilla-project.org/download.php">Filezilla</a>) and upload the content of the Template on your server root.</li>
					<li>Once the files are done uploading go to www.yourdomainname.com/index.html</li>
				</ol>
			</div>
		</section>
		<section id="tmpl-structure">
			<h2 class="title">Template Structure</h2>
			<p class="fifteen">All information within the main content area is nested within a body tag. The general template structure is pretty the same throughout the template. Here is the general structure of main page (index.html).</p>
			<pre class="brush: html">

				<header class="header_area"></header>
					<main class="site-main">
						<section class="section"></section>
						<section class="section"></section>
						<section class="section"></section>
					</main>
				<footer class="footer"></footer>

			</pre>
		</section>
		<section id="css-structure">
			<h2 class="title">CSS Files and Structure</h2>
			<p class="fifteen">These are the css files that are loaded into templates in <strong>Head Section</strong>.</p>
			<pre class="brush: html">
			
			<!-- CSS here -->
			
			<link rel="stylesheet" href="assets/css/bootstrap.min.css">
			<link rel="stylesheet" href="assets/css/owl.carousel.min.css">
			<link rel="stylesheet" href="assets/css/slicknav.css">
			<link rel="stylesheet" href="assets/css/flaticon.css">
			<link rel="stylesheet" href="assets/css/progressbar_barfiller.css">
			<link rel="stylesheet" href="assets/css/gijgo.css">
			<link rel="stylesheet" href="assets/css/animate.min.css">
			<link rel="stylesheet" href="assets/css/animated-headline.css">
			<link rel="stylesheet" href="assets/css/magnific-popup.css">
			<link rel="stylesheet" href="assets/css/fontawesome-all.min.css">
			<link rel="stylesheet" href="assets/css/themify-icons.css">
			<link rel="stylesheet" href="assets/css/slick.css">
			<link rel="stylesheet" href="assets/css/nice-select.css">
			<link rel="stylesheet" href="assets/css/style.css">
					
			</pre>

			<h2 class="title">Google Web Fonts</h2>
			<p>By default, the template loads this font from Google Web Font Services, you can change the font with the one that suits you best.</p>
			<pre class="brush:html">		
				                
			<!-- Google Font -->
			
			<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&family=Poppins:wght@200;300;400;500;600;700;800&display=swap"> 

			</pre>

			<p class="twenty">Remember to change the font into <strong>style.css</strong></p>
		</section>
		<section id="javascript">
			<h2 class="title">Javascript Files and Structure</h2>
			<p class="fifteen">These are the list of Javascript files that are loaded into templates in end of the <strong>Body Section</strong>.
			<pre class="brush: html">

				<!-- JS here -->

				<script src="./assets/js/vendor/modernizr-3.5.0.min.js"></script>
				<!-- Jquery, Popper, Bootstrap -->
				<script src="./assets/js/vendor/jquery-1.12.4.min.js"></script>
				<script src="./assets/js/popper.min.js"></script>
				<script src="./assets/js/bootstrap.min.js"></script>
				<!-- Jquery Mobile Menu -->
				<script src="./assets/js/jquery.slicknav.min.js"></script>

				<!-- Jquery Slick , Owl-Carousel Plugins -->
				<script src="./assets/js/owl.carousel.min.js"></script>
				<script src="./assets/js/slick.min.js"></script>
				<!-- One Page, Animated-HeadLin -->
				<script src="./assets/js/wow.min.js"></script>
				<script src="./assets/js/animated.headline.js"></script>
				<script src="./assets/js/jquery.magnific-popup.js"></script>

				<!-- Date Picker -->
				<script src="./assets/js/gijgo.min.js"></script>

				<!-- Video bg -->
				<script src="./assets/js/jquery.vide.js"></script>

				<!-- Nice-select, sticky -->
				<script src="./assets/js/jquery.nice-select.min.js"></script>
				<script src="./assets/js/jquery.sticky.js"></script>
				<!-- Progress -->
				<script src="./assets/js/jquery.barfiller.js"></script>
				
				<!-- counter , waypoint,Hover Direction -->
				<script src="./assets/js/jquery.counterup.min.js"></script>
				<script src="./assets/js/waypoints.min.js"></script>
				<script src="./assets/js/jquery.countdown.min.js"></script>
				<script src="./assets/js/hover-direction-snake.min.js"></script>

				<!-- contact js -->
				<script src="./assets/js/contact.js"></script>
				<script src="./assets/js/jquery.form.js"></script>
				<script src="./assets/js/jquery.validate.min.js"></script>
				<script src="./assets/js/mail-script.js"></script>
				<script src="./assets/js/jquery.ajaxchimp.min.js"></script>
				
				<!-- Jquery Plugins, main Jquery -->	
				<script src="./assets/js/plugins.js"></script>
				<script src="./assets/js/main.js"></script>
				
			</pre>
		</section>

		<section id="contact-form">
				<h2 class="title"> Contact Form </h2>
				<p>This is a PHP Script for sending messages to your email, you should replace <strong>demo@site.com</strong> to your email to start receive messages.</p>
				<pre class="brush:php">
					$to = 'demo@site.com'; // replace this mail with yours
					$firstname = $_POST["fname"];
					$email= $_POST["email"];
					$headers = 'MIME-Version: 1.0' . "\r\n";
					$headers .= "From: " . $email . "\r\n"; // Sender's E-mail
					$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

					$message ='<table style="width:100%">
						<tr>
							<td>'.$firstname.'  '.$laststname.'</td>
						</tr>
						<tr><td>Email: '.$email.'</td></tr>
					</table>';

					if (@mail($to, $email, $message, $headers))
					{
						echo 'The message has been sent.';
					}else{
					echo 'failed';
				}
			</pre>		            
		</section>
		<section id="subscription-form">
			<h2 class="title"> Subscription Form </h2>
			<p>Replace this action with your own mailchimp post URL. Don't remove the "". Just paste the url inside "".</p>
			<pre class="brush: javascript">
				<div id="mc_embed_signup">
					//Replace this action with your own mailchimp post URL. Don't remove the "". Just paste the url inside "".
					<form target="_blank" novalidate action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&id=92a4423d01" method="get" class="subscription relative d-flex justify-content-center"></form>
				</div>
			</pre>		            
		</section>
		<section id="video">
			<h2 class="title"> Video Tutorial </h2>
			<!-- 21:9 aspect ratio -->
			<div class="embed-responsive embed-responsive-21by9">
				<iframe class="embed-responsive-item" width="100%" height="515" src="https://www.youtube.com/embed/i7_PRPLOxVE?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
			</div>	            
		</section>
		<section id="credit">
			<h2 class="title">Source and Credit</h2>		            
			<div class="script-source">
				<ul>
					<li><a target="_blank" href="http://www.pexels.com">Pexels</a></li>
					<li><a target="_blank" href="http://jquery.com/">jQuery</a></li>
					<li><a target="_blank" href="http://getbootstrap.com">Bootstrap Framework</a></li>
					<li><a target="_blank" href="https://dimsemenov.com/plugins/magnific-popup/">magnific popup</a></li>
					<li><a target="_blank" href="https://masonry.desandro.com/">masonry</a></li>
					<li><a target="_blank" href="https://www.flaticon.com/home">flaticon</a></li>
					<li><a target="_blank" href="http://www.owlgraphic.com/owlcarousel">Owl Carousel</a></li>
					<li><a target="_blank" href="https://github.com/iamMonzurul/jQuery-AJAX-MailChimp">Ajax Mailchimp</a></li>
					<li><a target="_blank" href="http://fontawesome.io/">FontAwesome</a></li>
					<li><a target="_blank" href="https://themify.me/themify-icons">Themify Icons</a></li>
				</ul>
			</div>
		</section>
	</div>
</div>

<!-- Essential JavaScript Libraries
	==============================================-->
	<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="js/jquery.nav.js"></script>
	<script type="text/javascript" src="syntax-highlighter/scripts/shCore.js"></script> 
	<script type="text/javascript" src="syntax-highlighter/scripts/shBrushXml.js"></script> 
	<script type="text/javascript" src="syntax-highlighter/scripts/shBrushCss.js"></script> 
	<script type="text/javascript" src="syntax-highlighter/scripts/shBrushJScript.js"></script> 
	<script type="text/javascript" src="syntax-highlighter/scripts/shBrushPhp.js"></script> 
	<script type="text/javascript">
		SyntaxHighlighter.all()
	</script>
	<script type="text/javascript" src="js/custom.js"></script>

</body>
</html>

templates/form_errors.html
<!--login action이 실패했을 경우 어떠한 err인지 명세-->
{% if form.errors %}
<!--필드오류 부분-->
<!--user가 value를 이상하게 입력했을때의 err status-->
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{field.label}}></strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
<!--넌필드 오류-->
<!--user가 field의 값을 제대로 채워넣지 않았을때의 err-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
                <strong>{{ error }}></strong>
        </div>
    {% endfor %}
{% endif %}

templates/header.html
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>충북대학교 소프트웨어학과</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="{% static 'site.webmanifest'%}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--<link rel="stylesheet" href="assets/css/style.css">-->

</head>

<body>
    <!-- ? Preloader Start -->

    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/loder.png' %}" alt="">

                </div>
            </div>
        </div>
    </div>

    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a href="index.html"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">
                                                <li><a href="{% url 'sw:swintro'%}">학생회 소개</a>
                                                    <ul class="submenu">
                                                        <li><a href="{% url 'sw:swintro'%}">학생회 소개</a></li>
                                                        <li><a href="{% url 'sw:swhistory'%}">연혁</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="hosting.html">공지사항</a>
                                                    <ul class="submenu">
                                                        <li><a href="noticeone.html">공모전</a></li>
                                                        <li><a href="noticetwo.html">교내대회</a></li>
                                                        <li><a href="noticethree.html">학술 및 세미나</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="fleamarket.html">학생간 교류</a>
                                                    <ul class="submenu">
                                                        <li><a href="fleamarket.html">중고장터</a></li>
                                                        <li><a href="team-matching.html">팀 매칭</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="calendar.html">학생회 일정</a>
                                                <li><a href="help.html">Help</a></li>
                                                <li><a href="#">Blog</a>
                                                    <ul class="submenu">
                                                        <li><a href="blog.html">Blog</a></li>
                                                        <li><a href="blog_details.html">Blog Details</a></li>
                                                        <li><a href="elements.html">Element</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="contact.html">Contact</a></li>
                                                <!-- Button -->
                                                <li class="button-header margin-left "><a href="{% url 'account:create'%}"
                                                        class="btn">회원 가입</a></li>
                                                {% if user.is_authenticated %}
                                                <li class="button-header"><a href="{% url 'account:logout'%}" class="btn3">{{ user.username }} 님</a></li>
                                                {% else %}
                                                <li class="button-header"><a href="{% url 'account:login'%}" class="btn3">로그인</a></li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

templates/login.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> App landing</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="{% static 'site.webmanifest'%}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css'%}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
	<link rel="stylesheet" href="{% static 'css/slick.css'%}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/loder.png'%}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->


<main class="login-body" data-vide-bg="{% static 'img/login-bg.mp4'%}">
    <!-- Login Admin -->
    {% block content %}
    <form class="form-default" action="{% url 'account:login'%}" method="POST">
        <!--csrf firewall-->
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="login-form">
            <!-- logo-login -->
            <div class="logo-login">
                <a href="{% url 'sw:home'%}"><img src="{% static 'img/logo/loder.png'%}" alt=""></a>
            </div>
            <h2>로그인</h2>
            <div class="form-input">
                <label for="username">학번</label>
                <input  type="name" name="username" id="username" placeholder="학번" value="{{ frm.username.value|default_if_none:'' }}">
            </div>
            <div class="form-input">
                <label for="password">비밀번호</label>
                <input type="password" name="password" id="password" placeholder="비밀번호" value="{{form.password.value|default_if_none:''}}">
            </div>
            <div class="form-input pt-30">
                <input type="submit" name="submit" value="login">
            </div>
            
            <!-- Forget Password -->
            <a href="#" class="forget">Forget Password</a>
            <!-- Forget Password -->
            <a href="{% url 'account:create'%}" class="registration">Registration</a>
        </div>
    </form>
    {% endblock %}
    <!-- /end login form -->
</main>


    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>
    <!-- Video bg -->
    <script src="{% static 'js/jquery.vide.js'%}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/animated.headline.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script>

    <!-- Date Picker -->
    <script src="{% static 'js/gijgo.min.js'%}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.sticky.js'%}"></script>
    <!-- Progress -->
    <script src="{% static 'js/jquery.barfiller.js'%}"></script>
    
    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'js/hover-direction-snake.min.js'%}"></script>

    <!-- contact js -->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    </body>
</html>

templates/pybo/question_detail.html
<h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>

templates/pybo/question_list.html
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a></li>
        {% endfor %}
    </ul>
{% else %}
<p>질문이 없습니다</p>
{% endif %}